## Why NumPy? Numerical Python

- It's Fast
- written in C
- Vectorization via broadcasting (avoiding loops)

In [20]:
import numpy as np

### Datatypes and Attributes

In [21]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1
type(a1), a1.shape

(numpy.ndarray, (3,))

In [22]:
a2 = np.array([[1, 2],
            [3, 7.2]])
type(a2), a2.shape

(numpy.ndarray, (2, 2))

In [23]:
a1.ndim, a2.ndim

(1, 2)

In [24]:
a1.dtype, a2.dtype

(dtype('int64'), dtype('float64'))

In [25]:
a1.size, a2.size

(3, 4)

In [26]:
# Create a DataFrame from NumPy array

import pandas as pd

df = pd.DataFrame(a2)
df

0    1
0  1.0  2.0
1  3.0  7.2

### Create Array with NumPy

In [27]:
ones = np.ones((2, 3))

In [28]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
zeros = np.zeros((2, 3))

In [30]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [31]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [32]:
random_array

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0]])

In [33]:
random_array_2 = np.random.rand(5, 3) # or can use random.random
random_array_2

array([[0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102],
       [0.14335329, 0.94466892, 0.52184832],
       [0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 ]])

In [34]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4


array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing arrays and Metrices

In [35]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a1

array([1, 2, 3])

In [37]:
a1[0]

1

## NumPy in Action

In [40]:
# Import image and convert it to NumPy array
from matplotlib.image import imread
panda = imread("./images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [42]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)