## Why NumPy? Numerical Python

- It's Fast
- written in C
- Vectorization via broadcasting (avoiding loops)

In [1]:
import numpy as np

### Datatypes and Attributes

In [11]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1
type(a1), a1.shape

(numpy.ndarray, (3,))

In [12]:
a2 = np.array([[1, 2],
            [3, 7.2]])
type(a2), a2.shape

(numpy.ndarray, (2, 2))

In [10]:
a1.ndim, a2.ndim

(1, 2)

In [13]:
a1.dtype, a2.dtype

(dtype('int64'), dtype('float64'))

In [14]:
a1.size, a2.size

(3, 4)

In [15]:
# Create a DataFrame from NumPy array

import pandas as pd

df = pd.DataFrame(a2)
df

0    1
0  1.0  2.0
1  3.0  7.2

### Create Array with NumPy

In [18]:
ones = np.ones((2, 3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
zeros = np.zeros((2, 3))

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [23]:
random_array

array([[8, 8, 1, 1, 5],
       [8, 9, 6, 9, 4],
       [7, 2, 1, 3, 3]])

In [26]:
random_array_2 = np.random.rand(5, 3) # or can use random.random
random_array_2

array([[0.60481026, 0.58781867, 0.13788884],
       [0.67410175, 0.21996293, 0.11679482],
       [0.06754275, 0.10290492, 0.46784661],
       [0.17798009, 0.23918921, 0.8435992 ],
       [0.17779798, 0.03758939, 0.55232426]])

In [35]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4


array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])