## Why NumPy? Numerical Python

- It's Fast
- written in C
- Vectorization via broadcasting (avoiding loops)

In [3]:
import numpy as np

### Datatypes and Attributes

In [4]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1
type(a1), a1.shape

(numpy.ndarray, (3,))

In [5]:
a2 = np.array([[1, 2],
            [3, 7.2]])
type(a2), a2.shape

(numpy.ndarray, (2, 2))

In [6]:
a1.ndim, a2.ndim

(1, 2)

In [7]:
a1.dtype, a2.dtype

(dtype('int64'), dtype('float64'))

In [8]:
a1.size, a2.size

(3, 4)

In [9]:
# Create a DataFrame from NumPy array

import pandas as pd

df = pd.DataFrame(a2)
df

0    1
0  1.0  2.0
1  3.0  7.2

### Create Array with NumPy

In [10]:
ones = np.ones((2, 3))

In [11]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
zeros = np.zeros((2, 3))

In [13]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [14]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [15]:
random_array

array([[9, 1, 8, 2, 2],
       [3, 9, 2, 4, 9],
       [0, 9, 0, 2, 0]])

In [16]:
random_array_2 = np.random.rand(5, 3) # or can use random.random
random_array_2

array([[0.32021028, 0.01838342, 0.22879997],
       [0.16118216, 0.97600079, 0.40409625],
       [0.46003744, 0.95995   , 0.01881422],
       [0.36210427, 0.3029998 , 0.66050381],
       [0.88153269, 0.16645595, 0.39985077]])

In [17]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4


array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing arrays and Metrices

In [18]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a1

array([1, 2, 3])

In [20]:
a1[0]

1